#select and activate the required DB
USE admission;

#Creating a table with Attributes/Columns/Fields
CREATE TABLE Btech_Admission(
DATE_TIME datetime,
ADMISSION_ID varchar(9),
FIRST_NAME varchar(20),
LAST_NAME VARCHAR(20),
COURSE VARCHAR(10),
MOBILE int8,
PAF boolean,
PAF_AMOUNT decimal
);

#CREATING A NEW TABLE TEST_TABLE
CREATE TABLE TEST_TABLE(EID VARCHAR(5));

#DELETING THE TEST_TABLE CREATED RECENTLY
DROP TABLE test_table;

#RENAMING A TABLE NAME
RENAME TABLE test_table TO SAMPLE_TABLE;

#Adding a new Column to the Table betch admission
ALTER TABLE BTECH_ADMISSION
ADD PAF bool;

#Print the table
SELECT *
FROM BTECH_ADMISSION;

#Moving the column whats_app_number after email_id 
ALTER TABLE BTECH_ADMISSION
MODIFY WHATS_APP_NUMBER bigint
AFTER EMAIL_ID;

#RENAMING THE COLUMN DATE_TIME TO DAY
ALTER TABLE BTECH_ADMISSION
RENAME COLUMN DATE_TIME TO DAY;

#MOVE THE DAY COLUMN TO THE FIRST
ALTER TABLE BTECH_ADMISSION
MODIFY DAY datetime
FIRST;

#chamge the Data type of PAF froom bool to int
ALTER TABLE BTECH_ADMISSION
MODIFY COLUMN PAF INT;

#Delete or Drop the PAF column
ALTER TABLE BTECH_ADMISSION
DROP COLUMN PAF;



