#UPDATE AND DELETE DATA FROM A TABLE

#Selct and activate the respective DB
use ADMISSION;

#CREATING ANOTHER DATABASE
CREATE DATABASE MARKETTING;

#PRINTING ALL THE CURRENT TABLE OF THE BTECH_ADMISSION
SELECT *
FROM BTECH_ADMISSION;

#DELETING THE MOTHER_NAME COLUMN
ALTER TABLE BTECH_ADMISSION
DROP COLUMN MOTHER_NAME;

#Adding a NEW COLUMN NAMED UG
ALTER TABLE BTECH_ADMISSION
ADD COLUMN UG BOOL;

#SET THE UG VALUE TO TRUE FOR ALL THE ENTRIES
UPDATE BTECH_ADMISSION
SET UG=TRUE
WHERE ADMISSION_ID IS NOT NULL;

#SETTING UP VALUES IN PLACE OF NULL FOR A PARTICUCLAR ROW/ENTRY
UPDATE BTECH_ADMISSION
SET LAST_NAME="MIKE",
	EMAIL_ID="JHON@456"
WHERE ADMISSION_ID="AJU/200365";

#TO DELETE ALL THE ENTRIES/ROWS FROM THE TABLE
SELECT * FROM SAMPLE_TABLE;

#LETS ADD SOME COLUMN TO SAMPLE_TABLE FOLLOWED BY SOME ENTRIES
ALTER TABLE SAMPLE_TABLE
ADD COLUMN NAME VARCHAR(10),
ADD COLUMN AGE INT;

#Adding some entries to it
INSERT INTO SAMPLE_TABLE
VALUES ("E12","SAM",25),
	   ("E45","JIMMY",26),
       ("E96","RAM",21);
       
#NOW DELETE ALL THE ROWS FROM TABLE
DELETE FROM SAMPLE_TABLE;    #IT WILL DELETE ALL THE ENTRIES FROM TABLE

#DELETING SELECTIVE ROWS DEPENDING UPON SOME CONDITION OR MULTIPLE CONDITION
DELETE FROM BTECH_ADMISSION
WHERE DAY IS NULL OR COURSE IS NULL OR PAF_AMOUNT IS NULL; 
#THIS QUERRY WILL DELETE ONLY THOSE ROWS WHERE DAY IS NULL OR THE COURSE IS NULL OR THE PAF AMOUNT IS NULL

# all the ablove querry style is DML DATA MANIPULATION LANGUAGE
# MODIFICATION ALLOWED AT DATA LEVEL
# INSERT INTO , DELETE FROM , UPDATE <TABLE> SET XYZ="KK" WHERE ID=="DFJDJ"