#COMMIT-AUTO COMMIT-AND ROLLBACK
#BY DEFAULT AUTOCOMMIT IS SET ON IN MYSQL
#I.E WHATEVER TRANSACTION YOU PERFROM ITS BEING SAVED AUTOMATICALLY

# AND IF IN CASE WE DO A TRANSACTION WHICH WE MIGHT REGRET LATER ,AND WANT TO UNDO THAT TRANSACTION WE NEED TO SET AUTOCOMMIT = OFF
# THEN OUR TRANSACTION WON'T SAVE AUTOMATICALLY AND WE NEED TO MANUALLY SAVE OUR TRANSACTION
USE ADMISSION;
SET AUTOCOMMIT=OFF;

SELECT *
FROM BTECH_ADMISSION;

COMMIT;

#BY ACCIDENT IF I DELETE THE ENTYIRE TABLE AT ONCE
DELETE FROM BTECH_ADMISSION;

#NOW PRINT THE TABLE
SELECT * FROM BTECH_ADMISSION;

#I WANT TO UNDO THE OPERATION AND REVERT BACK THE CHANGES SO DO ROLLBACK;
ROLLBACK;  #UNDO OPERATION

COMMIT;

SET AUTOCOMMIT=ON;

