#UNIQUE , NOT NULL CONSTRAIN IN COLUMNS OF A TABLE

USE ADMISSION;

SHOW TABLES;  #QUERRY THAT WILL LIST DOWN ALL THE TABLES INSIDE A DB
SHOW TABLE STATUS;  #QUERRY THAT WILL SHOW THE STATUS OF ALL THE TABLES ENGINE , VERSION , ROW  FORMAT ETC METADATA

SELECT *
FROM BTECH_ADMISSION;

#CREATING A NEW TABLE WITH NAME CATELOG
CREATE TABLE CATELOG
( PROD_ID VARCHAR(5) UNIQUE,
  PRODUCT_NAME VARCHAR(20) UNIQUE,
  PRODUCT_PRICE DECIMAL(4,2),
  IN_STOCK BOOLEAN
);
#Adding Unique constarin tells that duplicate same value cannot exits in that respective column

SELECT * FROM CATELOG;

#IN CASE IF A TABLE IS ALREADY BEING CREATED AND WE WANT TO IMPOSE THE UNIQUE CONSTRAIN
ALTER TABLE BTECH_ADMISSION
ADD CONSTRAINT
UNIQUE (ADMISSION_ID,EMAIL_ID);  
#NOW ADMISSION ID AND EMAIL ID COLUMN VALUES SHOULD BE UNIQUE FOR ALL THE ENTRIES

#TRYINFG TO INSERT SOME DUPLICATE ENTRIES IN CATELOG
INSERT INTO CATELOG
VALUES
("P25","BRAKE OIL",45.23,TRUE),
("P45","BULB",10.23,FALSE),
("P12","BULB",8.14,TRUE);
#ERROR RAISED ERROE CODE 1062

INSERT INTO CATELOG
VALUES
("P25","BRAKE OIL",45.23,TRUE),
("P45","BULB",10.23,FALSE),
("P12","PINS",8.14,TRUE);  #NO ERROR RAISED

#****************************** NULL , NOT NULL CONSTRAIN **************************************************

#creating a new table with NULL AND NOT NULL CONSTRAIN
CREATE TABLE TABLE_1
( EMP_ID INT NOT NULL,
  EMP_NAME VARCHAR(25),
  EMP_EMAIL VARCHAR(50) NOT NULL,
  EMP_SALARY DECIMAL(4,2)
);
SELECT * FROM TABLE_1;

#Adding Not null constrain to an existsing Table
SELECT * FROM SAMPLE_TABLE;
ALTER TABLE SAMPLE_TABLE
MODIFY NAME VARCHAR(10) NOT NULL;

#******************************************CHECK CONSTRAINT**********************************************************

#Adding check constraint to a newly created table
CREATE TABLE TABLE_2
(ID VARCHAR(5),
NAME VARCHAR(50),
SALARY DECIMAL(6,2),
PHONE_NUMBER BIGINT,
CONSTRAINT salary_validator CHECK (SALARY>=1000.00 AND SALARY<=9999.99)
);

SELECT VERSION();  #shwos the version of Mysql 
SHOW TABLE STATUS;


#Adding the Check constraint to an already created Table
SELECT * FROM BTECH_ADMISSION;

ALTER TABLE BTECH_ADMISSION
ADD CONSTRAINT course_checker CHECK (COURSE IN ("CSE","BBA","BCA","LLM","PHRM","BCOM","BTECH"));

#LETS TRY TO ADD AN COURSE OTHER THAN THE CHECK ASSIGNED ABOVE
INSERT INTO BTECH_ADMISSION
VALUE
(now(),"AJU/200367","KIM","DAVID","OPC@GMAIL.COM",8236654774,"MTECH",NULL,NULL);
#Gives an ERROR THAT CHECK constraint is Violated 

#Now insert a legal values as per all the constraint
#Inserting only selected attributes
INSERT INTO BTECH_ADMISSION(DAY,ADMISSION_ID,COURSE)
VALUE
(now(),"AJU/200749","LLM");  #EVERYTHING WORKS FINE

#DELETING A CONSTRAINT
#DELETING THE SALARY CONSTRAINT USED IN TABLE_2 
ALTER TABLE TABLE_2
DROP CONSTRAINT salary_validator;   #Refering the CHECK using the alis we created it for

#******************************************************DEFAULT CONSTRAINT*******************************************************
#IF INSERTING A ROW AND DO NOT ADD A VALUE TO A GIVEN COLUMN THEN DEFAULT CONSTRAINT WILL ADD THAT RESPECTIVE DEAFULT VALUE IN THAT COLUMN;

#ADDING DEFAULT CONTRAINT TO A NEWLY CREATED TABLE
CREATE TABLE TRANSACTION_RECORD
(TRANSACTION_ID VARCHAR(20) UNIQUE,
AMOUNT DECIMAL(8,2),
DATE_TIME DATETIME DEFAULT NOW(),
CONSTRAINT amount_validator CHECK (AMOUNT>=0.05 AND AMOUNT<=100000.00));
SELECT * FROM TRANSACTION_RECORD;

#ADDING DEFAULT CONSTRAINT TO ALREADY EXISTING TABLE
ALTER TABLE BTECH_ADMISSION
ALTER PAF_AMOUNT SET DEFAULT 1000,
ALTER UG SET DEFAULT TRUE;

#NOW WE WILL ADD 2 NEW ROWS BY SKIPPING THE PAF_AMOUNT 
INSERT INTO BTECH_ADMISSION(DAY,ADMISSION_ID,FIRST_NAME,COURSE)
VALUES
(NOW(),"AJU/200412","MIKE","BBA"),
(NOW(),"AJU/200562","NANCY","BTECH");







