#UNIQUE , NOT NULL CONSTRAIN IN COLUMNS OF A TABLE

USE ADMISSION;

SHOW TABLES;  #QUERRY THAT WILL LIST DOWN ALL THE TABLES INSIDE A DB
SHOW TABLE STATUS;  #QUERRY THAT WILL SHOW THE STATUS OF ALL THE TABLES ENGINE , VERSION , ROW  FORMAT ETC METADATA

SELECT *
FROM BTECH_ADMISSION;

#CREATING A NEW TABLE WITH NAME CATELOG
CREATE TABLE CATELOG
( PROD_ID VARCHAR(5) UNIQUE,
  PRODUCT_NAME VARCHAR(20) UNIQUE,
  PRODUCT_PRICE DECIMAL(4,2),
  IN_STOCK BOOLEAN
);
#Adding Unique constarin tells that duplicate same value cannot exits in that respective column

SELECT * FROM CATELOG;

#IN CASE IF A TABLE IS ALREADY BEING CREATED AND WE WANT TO IMPOSE THE UNIQUE CONSTRAIN
ALTER TABLE BTECH_ADMISSION
ADD CONSTRAINT
UNIQUE (ADMISSION_ID,EMAIL_ID);  
#NOW ADMISSION ID AND EMAIL ID COLUMN VALUES SHOULD BE UNIQUE FOR ALL THE ENTRIES

#TRYINFG TO INSERT SOME DUPLICATE ENTRIES IN CATELOG
INSERT INTO CATELOG
VALUES
("P25","BRAKE OIL",45.23,TRUE),
("P45","BULB",10.23,FALSE),
("P12","BULB",8.14,TRUE);
#ERROR RAISED ERROE CODE 1062

INSERT INTO CATELOG
VALUES
("P25","BRAKE OIL",45.23,TRUE),
("P45","BULB",10.23,FALSE),
("P12","PINS",8.14,TRUE);  #NO ERROR RAISED

#****************************** NULL , NOT NULL CONSTRAIN **************************************************




