#***********************AUTO UPDATE**************************
# SETTING AUTO-INCREMENT WHEN CREATING A TABLE
# BY-DEFAULT THE AUTO INCREMENT IS AWLAYS GOING TO BE 1
# Atmost only one column can be AI , and that too it should be a key;
CREATE TABLE TABLE_1
(ID INT PRIMARY KEY AUTO_INCREMENT,
AMOUNT DECIMAL(7,2) NOT NULL,
CONSTRAINT amount_validate CHECK (AMOUNT>=10000.00 AND AMOUNT<=99999.99)
);
#CHANGEING THE DEFAULT VALUE OF THE AUTO KEY FROM 1 TO 100
ALTER TABLE table_1
AUTO_INCREMENT = 100;

SELECT * FROM TABLE_1;

#INSERT VALUES INTO TABLE_1
INSERT INTO TABLE_1(AMOUNT)
VALUE(51400.56);