#**************************** AGGREGATE FUNCTION *********************************************
# count function : This Function counts all the Non-Null entries of a given Attribute

#DISPLAY THE STUDENT_DETAILS TABLE
SELECT * 
FROM STUDENT_DETAILS;

#COUNT ALL THE NON-NULL ENTRIES IN THE COURSE_ID
SELECT COUNT(COURSE_ID)
FROM STUDENT_DETAILS;

#COUNT ALL THE NULL ENTRIES IN THE COURSE_ID
SELECT COUNT(COURSE_ID) AS COUNT_COURSE_ID
FROM STUDENT_DETAILS
WHERE COURSE_ID IS NULL;

#****************************** SUM , AVG , MAX ,MIN ******************************************
SELECT SUM(COURSE_FEE) AS TOTAL_COURSE_FEE,MIN(COURSE_FEE),MAX(COURSE_FEE),AVG(COURSE_FEE)
FROM COURSE_DETAILS;

#***************************** CONACT FUNCTION*************************
SELECT * 
FROM BTECH_ADMISSION;

SELECT concat(FIRST_NAME," ",LAST_NAME) AS FULL_NAME
FROM BTECH_ADMISSION
WHERE FIRST_NAME IS NOT NULL AND LAST_NAME IS NOT NULL;

CREATE VIEW BTECH_FULL_VIEW AS
SELECT * , CONCAT(FIRST_NAME," ",LAST_NAME) AS FULL_NAME
FROM BTECH_ADMISSION;

SELECT * FROM BTECH_FULL_VIEW;   #Alias of the View is BTECH_FULL_VIEW
#IN VIEW WE DO NOT ACTUALLY IMPLEMENT THAT MODIFICATION THE ORIGINAL TABLE WE JUST CREATE A 
#SHOW SAMPLE TABLE (WITH A NAME (VIEW NAME) ALIAS) AS OF HOW THE TABLE WILL LOOK LIKE AFTER THE MODIFICATION

#IF WE ACTUALLY WANT TO ADD THE FULL_NAME COLUMN IN THE ACTUAL TABLE
#THEN UPDATE THE TABLE
ALTER TABLE BTECH_ADMISSION
ADD COLUMN FULL_NAME VARCHAR(50);

UPDATE BTECH_ADMISSION
SET FULL_NAME = CONCAT(FIRST_NAME," ",LAST_NAME);
#NOW THE ACTUAL TABLE WILL TOO CONTAIN THIS NEW COLUMN FULL_NAME;
