#***************************** WILD CARD CHARACTER % *********************************
#USE TO SUBSTITUTE ONE OR MORE CHARACTER , JUST LIKE REGULAR EXPRESSIONS
# % SIGN = ZERO OR MORE CHARACTER (*)
# UNDERSCORE _ : EXACTLY ONE CHARACTER

#FIND THE NAME OF ALL THREE LENGTH STUDENTS
SELECT STUDENT_NAME
FROM student_details
WHERE STUDENT_NAME LIKE "___";

#FIND THE NAME OF ALL THE STUDENTS STARTING WITH LETTER A
SELECT STUDENT_NAME
FROM STUDENT_DETAILS
WHERE STUDENT_NAME LIKE "A%";