#*************************** ORDER BY CALUSE***********************
#default is Ascending

SELECT STUDENT_NAME,COURSE_ID
FROM STUDENT_DETAILS
ORDER BY  COURSE_ID;

SELECT * FROM admission.btech_admission;

SELECT EMAIL_ID,PAF_AMOUNT
FROM BTECH_ADMISSION
ORDER BY PAF_AMOUNT,FIRST_NAME;
#THE RESULT IS SORTED BASED ON THE PAF_AMOUNT VALUE IF CONFLICT OCUURS THEN WE USE THE FIRST_NAME COLUMN TO RESOLVE IT

