#**************************************** LIMIT CLAUSE ************************************************
# LIMIT CLAUSE IS USED TO LIMIT THE NUMBER OF RECORDS
# USEFUL IF YOU ARE WORKING WITH A LOT OF DATA
# CAN BE USED TO DISPLAY LARGE DATA ON PAGES (PAGINATION)
SELECT * FROM admission.btech_admission;

INSERT INTO BTECH_ADMISSION
VALUES
(NOW(),"AJU/205698","JERRY","MIKE","JERR@GMAIL.COM",NULL,"BBA",6500.00,1,"JERRY MIKE"),
(NOW(),"AJU/205498","JHONES","OPUS","JHONS@GMAIL.COM",7203245965,"BTECH",4500.00,1,"JHONES OPUS"),
(NOW(),"AJU/204998","FRED","COW","FRR@GMAIL.COM",9065237766,"BCA",9500.00,1,"FRED COW");

SELECT FULL_NAME
FROM btech_admission
WHERE FULL_NAME IS NOT NULL
ORDER BY LAST_NAME LIMIT 5;

SELECT FULL_NAME
FROM BTECH_ADMISSION
WHERE FULL_NAME IS NOT NULL 
AND PAF_AMOUNT > 5000
LIMIT 3;