#**************************************** SET OPERATORS ********************************************
#SET OPERATIONS POSSIBLE IFF
#1. WHEN TWO OR MORE OF THE TABLES HAVE THE SAME ARITY/DEGREE
#2. Domain of Attribute of Both or more of the table should be same

#************************ UNION , UNION ALL OPERATOR *************************************
SELECT COURSE_ID 
FROM STUDENT_DETAILS
UNION
SELECT COURSE_ID
FROM COURSE_DETAILS;
#UNION WILL INDCLUDE DUPLICATE ONLY ONCE

#UNION ALL WILL INCLUDE ALL THE DUPLICATES
SELECT COURSE_ID 
FROM STUDENT_DETAILS
UNION ALL
SELECT COURSE_ID
FROM COURSE_DETAILS;

#*******************************  INTERSECT ************************************
#MY SQL Traditionally does not support INTERSECT AND INTERSEACT ALL directly
#INTERSECT IS ACHIVED VIA INNER JOIN or IN operator

SELECT DISTINCT STUDENT_DETAILS.COURSE_ID
FROM STUDENT_DETAILS INNER JOIN COURSE_DETAILS
WHERE STUDENT_DETAILS.COURSE_ID = COURSE_DETAILS.COURSE_ID;

#Another way using IN OPERATOR
SELECT DISTINCT COURSE_ID
FROM STUDENT_DETAILS
WHERE COURSE_ID 
IN
(SELECT COURSE_ID
FROM COURSE_DETAILS);

#******************************* MINUS **************************
#MINUS is not supported directly we would use NOT IN to achieve this
# A-B AND B-A
SELECT COURSE_ID
FROM COURSE_DETAILS
WHERE COURSE_ID
NOT IN
(SELECT COURSE_ID
FROM STUDENT_DETAILS
WHERE COURSE_ID IS NOT NULL);

#Another way using LEFT JOIN
SELECT COURSE_DETAILS.COURSE_ID
FROM COURSE_DETAILS LEFT JOIN STUDENT_DETAILS
ON student_details.COURSE_ID = course_details.COURSE_ID
WHERE STUDENT_DETAILS.COURSE_ID IS NULL;
#A-B LEFT-RIGHT TABLE WHERE THE LEFT TABLE IS COURSE_DETAILS AND RIGHT TABKE IS STUDENT_DETAILS
#THIS WILL COMBINE ALL THE TUPLES FROM A AND B BASED ON THE INNER JOIN OF A.COURSEID=B.COURSE_ID
#AS WELL BRING ALL THE LEFTOUT FROM THE LEFT ONE
#AND THE LEFTOUT FROM LEFT ONE WILL ALWAYS HAVE NULL ENTRIES IN THE RIGHT TABLE COLUMNS