#**************************************** VIEW **********************************************
#A VIEW IS JUST A PSEUDO-REPRESENTATION OR A TRIAL-DEMO REPRESENTATION OF THE TABLE
#IT IS A VIRTUAL TABLE BASED ON THE RESULT-SET OF AN SQL STATEMENT
#OF HOW THE EXISTING TABLE WILL LOOK AFTER PERFROMING THE REQUIRED MODIFICATION
#IT IS NOT A REAL TABLE BUT BEHAVE AS ONE
#ANY CHANGE MADE IN THE ORIGINAL TABLE WILL ALSO UPDATE THE VIEW
#AS WELL AS WE CAN MODIFY AND PERFORM OPERATIONS IN OUR VIEW TABLE WITHOUT AFFECTING THE ORIGINAL ONE
#THEY ARE NOT REAL TABLES , BUT CAN BE INTERACTED WITH AS IF THEY WERE 

#DISPLAY THE BTECH_ADMISSION TABLE
SELECT *
FROM btech_admission;

#I WANT TO CREATE A VIEW OF THOSE ADMISSION_ID AND FULL NAME WHO ARE ELIGIBLE FOR DISCOUNT
CREATE VIEW BTECH_ADMISSION_DISCOUNT AS
SELECT ADMISSION_ID,FULL_NAME
FROM BTECH_ADMISSION
WHERE PAF_AMOUNT>4000 AND FULL_NAME IS NOT NULL;

#TO DELETE A VIEW USE THE QUERRY
DROP VIEW btech_admission_discount;