#******************************************* INDEX ******************************************************
#INDEX IMPLEMENTED VIA THE B-TREE DATA STRUCTURE
#INDEXS ARE USED TO FIND VALUE WITHIN A SPECIFIC COLUMN MORE QUICLY
#MY-SQL NORMALLY SEARCHES SEQUENTALLY THROUGH A COLUMN
-- The longer the column the more expensive the operation is
-- UPDATE takes more time , SELECT takes less time

# to show the current indexes of a table
SHOW INDEXES FROM student_details;
#IT SHOWS THAT THERE'S AN EXITSING INDEX OVER THE PK OF THE TABLE
#AS A RESULT SEARCH VIA THE SID (PK) WOULD BE VERY FAST
#BUT WHAT IF WE WANT TO SEARCH SOME TUPLES VIA ANOTHER NON-PK ATTRIBUTE THEN WE NEED TO APPLY INDEX OVER THAT ATTRIBUTE
#TO MAKE THAT SEARCH MORE EFFICIENT

SELECT * FROM student_details;

#ADDED SOME MORE VALUES INTO THE TABLE
INSERT INTO student_details
VALUES
(NOW(),"S71","TIM","TIM@GMAIL.COM","C45"),
(NOW(),"S07","GUPPY","GUP@GMAIL.COM",NULL),
(NOW(),"S11","FLINT","FLINT@GMAIL.COM","C23"),
(NOW(),"S40","MARKOV","MARK@GMAIL.COM","C20");

CREATE INDEX NAME_IDX
ON student_details(STUDENT_NAME);

#TO DELETE AN INDEX 
ALTER TABLE student_details
DROP INDEX NAME_IDX;