-- ********************************************** GROUP BY CLAUSE *********************************************************
-- EVERY ATTRIBUTE OF GROUP BY CLAUSE MUST BE PRESENT IN THE SELECT CLAUSE
-- NOT ALLOWED TO SELECT(PRESENT) OTHER ATTRIBUTE IN THE SELECT CLAUSE
-- WHEN AGGREGERATE OPERATOR AND OTHER ATTRIBUTE USED IN THE SELECT CLAUSE
-- THAT OTHER ATTRIBUTE MUST BE PRESENT IN THE GROUP BY CLAUSE

SELECT * FROM btech_admission;

SELECT COURSE
FROM btech_admission
WHERE COURSE IS NOT NULL
GROUP BY COURSE;

#THIS WILL RAISE ERROR
-- BECAUSE EVERY ATTRIBUTE OF GROUP BY CLAUSE MUST BE PRESENT IN THE SELECT CLAUSE
SELECT ADMISSION_ID
FROM btech_admission
WHERE COURSE IS NOT NULL
GROUP BY COURSE;

SELECT DAY AS DATE_TIME ,COUNT(ADMISSION_ID) AS TOTAL_ADMISSION
FROM btech_admission
GROUP BY DAY;

SELECT COURSE,SUM(PAF_AMOUNT) AS TOTAL_REVENU
FROM btech_admission
WHERE COURSE IS NOT NULL
GROUP BY COURSE
ORDER BY TOTAL_REVENU DESC;


#SELECT ALL THOSE COURSES WHOSE AVERAGE COLLECTIONS ARE MORE THAN THE AVERAGES COLLECTIONS OF ALL THE COMBINED COURSES
SELECT COURSE
FROM btech_admission
WHERE COURSE IS NOT NULL
GROUP BY COURSE
HAVING AVG(PAF_AMOUNT)>
(SELECT AVG(PAF_AMOUNT)
FROM btech_admission);

#PRINT THE AVERAGE COLLECTIONS OF ALL THE COURSES TILL NOW
SELECT COURSE,AVG(PAF_AMOUNT) AS AVERAGE_COLLECTION
FROM BTECH_ADMISSION
WHERE COURSE IS NOT NULL AND PAF_AMOUNT IS NOT NULL
GROUP BY COURSE
ORDER BY AVERAGE_COLLECTION DESC;

#PRINT TOTAL NUMBER OF STUDENTS IN EACH AND EVERY COURSE
SELECT COURSE , COUNT(COURSE) AS TOTAL_NUMBER
FROM btech_admission
WHERE COURSE IS NOT NULL
GROUP BY COURSE;

-- ********************************** ROLLUP ******************************
-- EXTENSION OF THE GROUP BY CLAUSE
-- PRODUCES ANOTHER ROW AND SHOWS THE GRAND-AGGREGERATE VALUE
SELECT COURSE , COUNT(COURSE) AS TOTAL_NUMBER
FROM btech_admission
WHERE COURSE IS NOT NULL
GROUP BY COURSE WITH ROLLUP;

SELECT COURSE,AVG(PAF_AMOUNT) AS AVERAGE_COLLECTION
FROM BTECH_ADMISSION
WHERE COURSE IS NOT NULL AND PAF_AMOUNT IS NOT NULL
GROUP BY COURSE WITH ROLLUP;