-- ***************************** NESTED-SUB QUERRIES *****************************************
SELECT * FROM COURSE_DETAILS;

#PRINT THE COURSE_ID AND NAME OF ALL THOSE SCORE WHOSE FEE ARE MORE THAN THE AVERAGE FEE
SELECT COURSE_ID,COURSE_NAME
FROM COURSE_DETAILS
WHERE COURSE_FEE >
(SELECT AVG(COURSE_FEE)
FROM COURSE_DETAILS);

#PRINT ALL THE NAME OF COURSE IN WHICH ATLEAST ONE STUDENT HAVE ENROLLED ON
SELECT COURSE_ID,COURSE_NAME
FROM COURSE_DETAILS
WHERE COURSE_ID IN
(SELECT COURSE_ID 
FROM STUDENT_DETAILS
WHERE COURSE_ID IS NOT NULL);