#********************PRIMARY KEY CONSTRAIN*********************
#PRIMARY KEY IS ALWAYS UNIQUE AND NOT NULL AND ATMOST ONE PK IS POSSIBLE IN ANY TABLE
#BY DEFAULT A TABLE WILL ALWAYS BE SORTED VIA PK

#Defining a PK when creating a table
CREATE TABLE TRANSACTION_RECORD
(TRANSACTION_ID VARCHAR(3) PRIMARY KEY,
AMOUNT DECIMAL(7,2),
TIME_STAMP DATETIME DEFAULT NOW(),
CONSTRAINT amount_validator CHECK (AMOUNT>=10000.00 AND AMOUNT<=99999.99)
);

#ADDING PK IN AN ALREADY DEFINED TABLE
ALTER TABLE btech_admission
ADD CONSTRAINT
PRIMARY KEY (ADMISSION_ID);
#SETTING ONLY ADMISSION_ID AD THE PRIMARY KEY , WE CAN ADD MULTIPLE KEY AS PK DEPENDING UPON THE FD 

#Will attempt to add a Admission ID which is already existing
INSERT INTO btech_admission(DAY,ADMISSION_ID,FIRST_NAME)
VALUES
(NOW(),"AJU/200540","SALT"),
(NOW(),"AJU/200366","TIM"),
(NOW(),"AJU/200456","RUSSEL");
#ERROR RAISED CODE 1062 DUPLICATE ENTRY

#THIS WILL WORK FINE
INSERT INTO btech_admission(DAY,ADMISSION_ID,FIRST_NAME)
VALUES
(NOW(),"AJU/200549","SALT"),
(NOW(),"AJU/200366","TIM"),
(NOW(),"AJU/200456","RUSSEL");

-- REMOVING PK FROM A TABLE
ALTER TABLE BTECH_ADMISSION
DROP PRIMARY KEY;
