SELECT *
FROM SUPERSTORE
LIMIT 5;

SELECT * 
FROM STUDENTS
LIMIT 5;

SELECT DISTINCT CITY
FROM SUPERSTORE;

SELECT COUNT(DISTINCT CITY)
FROM SUPERSTORE;

SELECT SEGMENT , CITY
FROM SUPERSTORE;

SELECT COUNT(DISTINCT CITY) AS CITY_COUNT
FROM SUPERSTORE;

SELECT *
FROM CLOTHINGS
LIMIT 10;

SELECT WASH_TYPE , ORIGIN , SIZE
FROM CLOTHINGS
WHERE MATERIAL = "COTTON"
LIMIT 10;

SELECT DISTINCT ORIGIN
FROM CLOTHINGS;

SELECT DISTINCT GARMENT
FROM CLOTHINGS
WHERE ORIGIN = "INDIA";

USE INFORMATION;

SELECT DISTINCT GARMENT
FROM CLOTHINGS
WHERE ORIGIN = "INDIA";


SELECT SIZE
FROM CLOTHINGS
WHERE COLOR = "RED" or COLOR ="GREEN";

SELECT *
FROM CLOTHINGS;

SELECT DISTINCT BRAND
FROM CLOTHINGS;

SELECT COUNT(DISTINCT BRAND)
FROM CLOTHINGS;

SELECT DISTINCT BRAND
FROM CLOTHINGS
WHERE ORIGIN="INDIA"
ORDER BY BRAND;

SELECT COUNT(DISTINCT BRAND)
FROM CLOTHINGS
WHERE ORIGIN="INDIA";
#ORDER BY BRAND;

SELECT *
FROM CLOTHINGS;

SELECT DISTINCT PRICE
FROM CLOTHINGS
ORDER BY PRICE;

SELECT MAX(PRICE)
FROM CLOTHINGS
WHERE COLOR="red";

#Querry to find the max AND MIN PRICE OF CORRESPONDING COLORS
SELECT COLOR , MAX(PRICE) AS MAX_PRICE , MIN(PRICE) AS MIN_PRICE
FROM CLOTHINGS
GROUP BY COLOR
ORDER BY COLOR;

#Querry to filter all those brands who name start with A
SELECT DISTINCT BRAND
FROM CLOTHINGS
WHERE BRAND LIKE "A%"
ORDER BY BRAND;


#Finding the Max and Min Price of respective brands
SELECT BRAND , MIN(PRICE) AS MIN_PRICE , MAX(PRICE) AS MAX_PRICE
FROM CLOTHINGS
GROUP BY BRAND
ORDER BY BRAND;

SELECT BRAND , ROUND(AVG(PRICE),2)
FROM CLOTHINGS
GROUP BY BRAND
ORDER BY BRAND;

SELECT SIZE , AVG(PRICE)
FROM CLOTHINGS
WHERE ORIGIN="INDIA"
GROUP BY SIZE
ORDER BY SIZE;

#fINDING THE mINIMUM AND MAXIMUM PRICE OF THE CORRESPONDING COUNTRY

SELECT ORIGIN , ROUND(MIN(PRICE),2) , ROUND(MAX(PRICE),2)
FROM CLOTHINGS
GROUP BY ORIGIN
ORDER BY ORIGIN;

SELECT DISTINCT BRAND
FROM CLOTHINGS
WHERE SEASON = "WINTER";

SELECT GARMENT , ROUND(AVG(PRICE),2)
FROM CLOTHINGS
WHERE SEASON="WINTER"
GROUP BY GARMENT
ORDER BY GARMENT;

SELECT DISTINCT BRAND
FROM CLOTHINGS
WHERE SEASON = "WINTER" AND PRICE > (
SELECT ROUND(AVG(PRICE),2)
FROM CLOTHINGS 
WHERE SEASON="WINTER");

SELECT BRAND
FROM CLOTHINGS
GROUP BY BRAND
ORDER BY BRAND;

show databases;
