#A SCRIPT TO TEST AND PRACTISE SQL SCRIPTS
# TO LEARN AND GROW

USE ADMISSION;

CREATE DATABASE TEST_AND_FUN;

USE TEST_AND_FUN;

CREATE TABLE TABLE_1
(
DATE_TIME DATETIME UNIQUE,
NAME VARCHAR(50),
COURSE VARCHAR(10),
PHONE_NUMBER INT8 UNIQUE,
DOB DATE
);

SHOW TABLES;

ALTER TABLE TABLE_1
ADD CONSTRAINT
UNIQUE (COURSE);

SELECT * FROM TABLE_1;

#NOW ADD AN EXTRA COLUMN WITH UNQOUE CONSTRAINT
ALTER TABLE TABLE_1
ADD COLUMN ADHAR_NUMBER INT8 UNIQUE;


#MODIFY THE DATATYPE OF DATE_TIME COLUMN TO DATE ONLY
ALTER TABLE TABLE_1
MODIFY COLUMN DATE_TIME DATE;

#RENAME THE NAME COULMN TO FULL_NAME
ALTER TABLE TABLE_1
RENAME COLUMN NAME TO FULL_NAME;

SELECT * FROM TABLE_1;

#MOVE THE COURSE COLUMN TO THE LAST
ALTER TABLE TABLE_1
MODIFY COLUMN COURSE VARCHAR(10)
AFTER ADHAR_NUMBER;

#DELETE THE COULMN DATE_TIME FROM TABLE_1
ALTER TABLE TABLE_1
DROP COLUMN DATE_TIME;

ALTER TABLE TABLE_1
DROP COLUMN ADHAR_NUMBER;
# ******************************************************************************************************************
#ADDING ROWS IN THE TABLE

INSERT INTO TABLE_1
VALUES
("BARON",9065785544,"2002-06-02","BCA"),
("ABIR",9012785544,"2002-06-12","BTECH"),
("BEN",9064785544,"2002-06-16","BCOM"),
("RAY",9065787544,"2002-06-22","BBA");

#INSERTING SEPECIFC COLUMN VALUES
INSERT INTO TABLE_1 (FULL_NAME,COURSE)
VALUES
("JAKE","DIPLOMA"),
("MADDY","FASH");

#DELETE A ROW
DELETE FROM TABLE_1
WHERE DOB IS NULL;

#UPDATE AN ENIRE COLUMN 
UPDATE TABLE_1
SET DOB = NULL;  #WILL CHANGE ALL THE DOB ENTRIES TO NULL

SELECT * FROM TABLE_1;

# *************************************************************************************************
CREATE TABLE TABLE_2
(TODAY_DATE DATE,
TODAT_DATE_TIME DATETIME,
TODAY_TIME TIMESTAMP
);

INSERT INTO TABLE_2
VALUES
(current_date(),now(),current_timestamp());

SELECT * FROM TABLE_2;

INSERT INTO TABLE_2
VALUE
(current_date(),now(),current_timestamp());

#*******************************************************************************************************
-- DDL practice CREATE ,ALTER , DROP
CREATE TABLE TABLE_3
(DATE_TIME DATETIME DEFAULT NOW(),
S_NAME VARCHAR(20),
S_DOB DATE,
PHONE BIGINT
);

SHOW TABLES;
SHOW TABLE STATUS;

# Adding Unique Constrain
ALTER TABLE TABLE_2
ADD CONSTRAINT
UNIQUE (TODAY_DATE_TIME);


# setting up check constraint
ALTER TABLE TABLE_2
ADD CONSTRAINT VALUE_CHECK CHECK (VALUE>=1000.00 AND VALUE<=9999.99);



#default constraint
ALTER TABLE TABLE_2
ALTER VALUE SET DEFAULT 1000.00;
